### ISSUE TITLE
后台新增商品时报错

### ISSUE THREAD

**Issue by Ais-Danny** [weiran1999/admin-manager#1]
报错内容

### Cause: java.sql.SQLSyntaxErrorException: Table 'cloud-mission-order.goods' doesn't exist
; bad SQL grammar []

就很奇怪cloud-mission-order下面就没有goods表

**Comment by weiraneve** [comment]
那个sql目录里的goods文件不对吗

**Comment by Ais-Danny** [comment]
> 那个sql目录里的goods文件不对吗

我检查了好像映射也是对的，就是不知道他怎么映射到cloud-mission-order下面goods表了，应该是cloud-mission-goods表下的goods吧

**Comment by weiraneve** [comment]
按理说确实嗷

**Comment by Ais-Danny** [comment]
![屏幕截图 2023-11-23 213306](https://github.com/weiraneve/admin-manager/assets/91066083/68e9d6ad-b0e2-4f16-858a-8ec7f670ad60)
这映射也看不出来啥问题呀，我进去调试了goodsMapper的，关于goods表的操作都会报一样的错

**Comment by Ais-Danny** [comment]
你自己那有没有这种情况

**Comment by weiraneve** [comment]
我现在没出现过，很早之前开发的时候好像有。

**Comment by weiraneve** [comment]
你把所有项目相关库和表都删一下，重新搞一遍试试

**Comment by weiraneve** [comment]
> 你自己那有没有这种情况

哥们所以你成功跑通了吗

**Comment by Ais-Danny** [comment]
> > 你自己那有没有这种情况
> 
> 哥们所以你成功跑通了吗

还是不行，你那有没有最新的数据库脚本

**Comment by weiraneve** [comment]
我check了下
问题出在
`GoodsMapper.xml` 中的`findGoods`方法，这个主要因为数据库的dynamic技术，本来这里不该调用order库的goods表，应该去找goods库的goods表的，这个问题我记得之前也出现过，我再看一下

**Comment by weiraneve** [comment]
`seckillcloud`的bug我已经修复了，已经push上去，可以重新拉取之后试试

**Comment by weiraneve** [comment]
如何嗷哥们

**Comment by Ais-Danny** [comment]
没啥大问题了，后面我再看看有没有其他问题
