### ISSUE TITLE
图片上传异常（试了各种规格图片）

### ISSUE THREAD

**Issue by Ais-Danny** [weiran1999/admin-manager#2]
![image](https://github.com/weiraneve/admin-manager/assets/91066083/ac392f1d-7c6b-4acf-b01d-331b3c6dcd10)
![image](https://github.com/weiraneve/admin-manager/assets/91066083/cb88386b-595b-4035-ae85-9e4215d7791d)

**Comment by weiraneve** [comment]
> ![image](https://private-user-images.githubusercontent.com/91066083/316205818-ac392f1d-7c6b-4acf-b01d-331b3c6dcd10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNTYyNjksIm5iZiI6MTcxMTE1NTk2OSwicGF0aCI6Ii85MTA2NjA4My8zMTYyMDU4MTgtYWMzOTJmMWQtN2M2Yi00YWNmLWIwMWQtMzMxYjNjNmRjZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDAxMDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NWU3NDExYzZiMzk2YmIxNDIxYzQ5ODUyYzRhN2I4MDEzZjczMjBiNmRjNjFhY2JmODA3NzVlNjc3NTVlNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7_NhRNmNSIwuVqD08nVSbEtcmmqp-8rlv7Z78gInKW4) ![image](https://private-user-images.githubusercontent.com/91066083/316205832-cb88386b-595b-4035-ae85-9e4215d7791d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNTYyNjksIm5iZiI6MTcxMTE1NTk2OSwicGF0aCI6Ii85MTA2NjA4My8zMTYyMDU4MzItY2I4ODM4NmItNTk1Yi00MDM1LWFlODUtOWU0MjE1ZDc3OTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDAxMDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYWMzZDIyNzI2NDY5MWRiODI5NzY4MDMyMGNmYWZhODBlZjEwZTlkNGI5YTgyZWQ1ODliNWYzYjlhNTlkMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3_x3zcmmEE0l9zmob5JYqY263QKILWhfLLgOhvtJo-Y)

这个应该是七牛的OSS配置失效了，我以前配置的是自己的七牛云服务。

**Comment by Ais-Danny** [comment]
同时秒杀刚新建的商品也无法秒杀成功，（但修改前面四个的秒杀时间又能正常秒杀）
![image](https://github.com/weiraneve/admin-manager/assets/91066083/bc9e3a5b-3cc8-428f-a13a-f32fb3477796)

**Comment by Ais-Danny** [comment]
那大佬能不能重新配置一下七牛的云存储，我这边没有备案的域名

**Comment by weiraneve** [comment]
<img width="923" alt="pic_success" src="https://github.com/weiraneve/admin-manager/assets/60456779/e897699f-2e94-4137-af12-bbff499c8b63">

我这边启动了之后，照片是能正常上传的

**Comment by weiraneve** [comment]
已解决
